In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Data sets Pre analysis

## Functions

In [2]:
# Define sensitive_data function
def sensitive_data(df):
  """Check sensitive data columns"""
  sus_kw = ["gender","race","ethnicity","pregnancy","zipcode","religion"]
  sensitive_cols = [c for c in df.columns if any(k in c.lower() for k in sus_kw)]
  return sensitive_cols

## Telcom Churn

In [16]:
# Load telcom data set
df_telcom = pd.read_csv(r"..\Data\Raw\Telco_Cusomer_Churn.csv")
display(df_telcom.head())
df_telcom.shape

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

(7043, 21)

In [4]:
# Check target proportions
print(df_telcom['Churn'].value_counts(normalize=True))

Churn
No     0.73463
Yes    0.26537
Name: proportion, dtype: float64

In [5]:
df_telcom.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='str')

Source: https://www.kaggle.com/datasets/blastchar/telco-customer-churn<br>
License: Data files © Original Authors<br>
Authors: -<br>
Collaborators: BlastChar (Owner)<br>

In [6]:
# Call the function
result = sensitive_data(df_telcom)
print(f"Potentially sensitive: {result}")

Potentially sensitive: ['gender']

## Bank Churn

In [20]:
# Load bank churn data set
df_bank = pd.read_csv(r"..\Data\Raw\Bank_churn.csv")
display(df_bank.head())
df_bank.shape

,id,CustomerId,Surname,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Rating,Exited,"Geography:str,Gender:str"
0,0.0,15674932.0,"O,k{wudilic_-huk>wu_",668.0,33.0,3.0,0.00,2.0,1.0,0.0,181449.97,-3,0,"{'Geography': 'Paris-France','Gender': 'Male'}"
1,1.0,15749177.0,"O{kwudi""li#%%'oli=-sa",627.0,33.0,1.0,0.00,2.0,1.0,1.0,49503.5,0,0,"{'Geography': 'Paris-France','Gender': 'Male'}"
2,2.0,15694510.0,Hsueh,678.0,40.0,10.0,0.00,2.0,1.0,0.0,184866.69,1,0,"{'Geography': 'Paris-France','Gender': 'Male'}"
3,3.0,15741417.0,"Kao,]?>?%]@",581.0,34.0,2.0,148882.54,1.0,1.0,1.0,84560.88,-4,0,"{'Geography': 'Paris-France','Gender': 'Male'}"
4,4.0,15766172.0,Ch-i]emen'-am,716.0,33.0,5.0,0.00,2.0,1.0,1.0,15068.83,-1,0,"{'Geography': 'Madrid-Spain','Gender': 'Male'}"

(165034, 14)

In [8]:
# Check target proportions
print(df_bank['IsActiveMember'].value_counts(normalize=True))

IsActiveMember
0.0    0.502325
1.0    0.497675
Name: proportion, dtype: float64

Source: https://www.kaggle.com/datasets/cat-reloaded-data-science/bank-customer-churn?resource=download<br>
License: Apache 2.0 (Can be used for academic projects.)<br>
Authors: Doaa Helal<br>
Collaborators: Doaa Helal, CAT Reloaded || Data Science circle (Owner)<br>

In [9]:
# Call the function
result = sensitive_data(df_bank)
print(f"Potentially sensitive: {result}")

Potentially sensitive: ['Geography:str,Gender:str']

## ISP Churn

In [14]:
# Load ISP dataset
df_isp = pd.read_csv(r"..\Data\Raw\internet_service_churn.csv")
display(df_isp.head())
df_isp.shape

,id,is_tv_subscriber,is_movie_package_subscriber,subscription_age,bill_avg,reamining_contract,service_failure_count,download_avg,upload_avg,download_over_limit,churn
0,15,1,0,11.95,25,0.14,0,8.4,2.3,0,0
1,18,0,0,8.22,0,NaN,0,0.0,0.0,0,1
2,23,1,0,8.91,16,0.00,0,13.7,0.9,0,1
3,27,0,0,6.87,21,NaN,1,0.0,0.0,0,1
4,34,0,0,6.39,0,NaN,0,0.0,0.0,0,1

(72274, 11)

In [11]:
# Check target proportions
print(df_isp['churn'].value_counts(normalize=True))

churn
1    0.554141
0    0.445859
Name: proportion, dtype: float64

Source: https://www.kaggle.com/datasets/mehmetsabrikunt/internet-service-churn<br>
License: CC0: Public Domain<br>
Authors: -<br>
Collaborators: Mehmet Sabri Kunt (Owner)<br>

In [12]:
# Call the function
result = sensitive_data(df_isp)
print(f"Potentially sensitive: {result}")

Potentially sensitive: []